version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:00"
      timezone: Japan
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "direct"
