- name: automatic merge for Dependabot pull requests
  conditions:
    - author~=^dependabot(|-preview)\[bot\]$
    - check-success=test
    - check-success=analyze
  actions:
    merge:
      method: merge
