version: 2.1

defaults: &defaults
  working_directory: ~/project
  executor:
    name: node/default
    tag: 10.16.0

orbs:
  node: circleci/node@1.1.3
  slack: circleci/slack@3.2.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependency
                command: yarn
          cache-key: yarn.lock
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Audit
          command: yarn audit
      - slack/status:
          fail_only: true

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  notify-status:
    executor: slack/alpine
    steps:
      - slack/status


workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches: { only: [master] }
    jobs:
      - install
      - audit: { requires: [install] }

  test:
    jobs:
      - install
      - test: { requires: [install] }
      - audit: { requires: [install] }
      - build: { requires: [test, audit] }
      - notify-status: { requires: [build] }
